In [208]:
import numpy as np
import pickle
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import CMR_IA as cmr
import sys

sys.path.append("../../Modeling/fitting")
from optimization_utils import make_boundary
from object_funcs import anal_perform_6b as anal_perform

In [209]:
SAVERES = False

## Load Stimuli and Semantic Matrix

In [210]:
with open("simu6b_data/simu6b_design.pkl", "rb") as inp:
    df_study = pickle.load(inp)
    df_test = pickle.load(inp)
df_study = df_study.loc[df_study.session < 100]  # for testing
df_test = df_test.loc[df_test.session < 100]

In [211]:
df_study

,study_itemno1,study_itemno2,study_item1,study_item2,list,session
0,120,459,BELT,DIAPER,0,0
1,1315,1260,SKETCH,SEAFOOD,0,0
2,357,723,COMPANION,HOSTESS,0,0
3,1551,1202,VEAL,ROCKET,0,0
4,1081,1066,PLANE,PIGMENT,0,0
...,...,...,...,...,...,...
7195,1019,1143,PASSAGE,PUPIL,5,99
7196,293,1375,CHERRY,STEAM,5,99
7197,871,927,MARKET,MOVIE,5,99
7198,1392,1486,STREAM,TORTOISE,5,99


In [212]:
df_test

,test_itemno1,test_itemno2,test_item,correct_ans,order,rep,test,list,session,test_pos,pair_idx
0,51,-1,ASTRONAUT,1083,2,1,1,0,0,1,8
1,1202,-1,ROCKET,1551,2,1,1,0,0,2,4
2,979,-1,OPERATOR,142,1,1,1,0,0,3,11
3,134,-1,BLADE,105,1,1,1,0,0,4,9
4,1081,-1,PLANE,1066,1,1,1,0,0,5,5
...,...,...,...,...,...,...,...,...,...,...,...
14395,1019,-1,PASSAGE,1143,1,1,2,5,99,20,7196
14396,487,-1,DOORBELL,788,2,1,2,5,99,21,7189
14397,723,-1,HOSTESS,1378,2,1,2,5,99,22,7192
14398,196,-1,BULLY,786,1,1,2,5,99,23,7190


In [213]:
s_mat = np.load("../wordpools/ltp_FR_similarity_matrix.npy")

## Run CMR-IA

In [214]:
# define parameters
params = cmr.make_default_params()
params.update(learn_while_retrieving=False, nitems_in_accumulator=96, use_new_context=True)

In [215]:
# load pso results
_, _, what_to_fit = make_boundary(sim_name="6b")
optim_params = np.loadtxt("simu6b_data/6b_250408_200-200.txt")
for pname, pvalue in zip(what_to_fit, optim_params):
    params[pname] = pvalue
params.update(beta_enc_inpair=0.05)  # learn_while_retrieving=False
params

{'beta_enc': 0.866662,
 'beta_rec': 0.550292,
 'beta_cue': 0.971412,
 'beta_rec_post': 0.082552,
 'beta_distract': 0.480264,
 'beta_enc_inpair': 0.05,
 'phi_s': 3.254107,
 'phi_d': 0.477546,
 's_cf': 0.367439,
 's_fc': 0.255119,
 'kappa': 0.188473,
 'eta': 0.001319,
 'omega': 6.681985,
 'alpha': 0.790381,
 'lamb': 0.103443,
 'c_thresh': 0.451522,
 'c_thresh_itm': 0.5,
 'c_thresh_assoc': 0.5,
 'd_assoc': 0,
 'rec_time_limit': 60000.0,
 'dt': 10,
 'nitems_in_accumulator': 96,
 'max_recalls': 50,
 'learn_while_retrieving': False,
 'use_new_context': True,
 'use_flexible_thresh': False,
 'psi_s': 0,
 'psi_c': 1,
 'c_s': 0,
 'thresh_sigma': 0,
 'ban_recall': None,
 'var_enc': 1,
 'bad_enc_ratio': 1,
 'recog_slope': 1,
 'gamma_fc': 0.360799,
 'gamma_cf': 0.345657}

In [216]:
# run the model
df_simu, f_in, f_dif = cmr.run_success_multi_sess(params, df_study, df_test, s_mat, mode="CR-CR")
# df_simu["test_pos"] = np.tile(np.arange(1, 25), 6000)
df_simu["test_pos"] = np.tile(np.arange(1, 25), 600)

# merge to get more info
df_simu = df_simu.merge(df_test, on=["session", "list", "test_itemno1", "test_itemno2", "test_pos"])
df_simu["correct"] = df_simu.s_resp == df_simu.correct_ans
df_simu

  0%|          | 0/100 [00:00<?, ?it/s]

100%|██████████| 100/100 [00:45<00:00,  2.21it/s]

CMR Time: 45.291598081588745


,session,list,test_itemno1,test_itemno2,s_resp,s_rt,csim,test_pos,test_item,correct_ans,order,rep,test,pair_idx,correct
0,0,0,51,-1,-1.0,-1.0,-1.000000,1,ASTRONAUT,1083,2,1,1,8,False
1,0,0,1202,-1,1551.0,3030.0,0.522379,2,ROCKET,1551,2,1,1,4,True
2,0,0,979,-1,-1.0,-1.0,-1.000000,3,OPERATOR,142,1,1,1,11,False
3,0,0,134,-1,-1.0,-1.0,-1.000000,4,BLADE,105,1,1,1,9,False
4,0,0,1081,-1,12.0,3870.0,0.535872,5,PLANE,1066,1,1,1,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14395,99,5,1019,-1,-1.0,-1.0,-1.000000,20,PASSAGE,1143,1,1,2,7196,False
14396,99,5,487,-1,788.0,1600.0,0.520041,21,DOORBELL,788,2,1,2,7189,True
14397,99,5,723,-1,-1.0,-1.0,-1.000000,22,HOSTESS,1378,2,1,2,7192,False
14398,99,5,196,-1,786.0,1380.0,0.583908,23,BULLY,786,1,1,2,7190,True


In [217]:
# get condition and congruence
df_cond = df_simu.groupby(["pair_idx", "test"])["order"].mean().to_frame(name="corr_rate").reset_index()
df_cond = df_cond.pivot_table(index="pair_idx", columns="test", values="corr_rate").reset_index()
df_cond.columns = ["pair_idx", "test1", "test2"]


def cond(x):
    test1 = x["test1"]
    test2 = x["test2"]
    if test1 == 1 and test2 == 1:
        return "F-F"
    elif test1 == 1 and test2 == 2:
        return "F-B"
    elif test1 == 2 and test2 == 1:
        return "B-F"
    elif test1 == 2 and test2 == 2:
        return "B-B"


df_cond["cond"] = df_cond.apply(lambda x: cond(x), axis=1)
df_cond["cong"] = df_cond.apply(lambda x: "Identical" if x["cond"] == "F-F" or x["cond"] == "B-B" else "Reversed", axis=1)
df_cond

,pair_idx,test1,test2,cond,cong
0,1,1.0,1.0,F-F,Identical
1,2,2.0,1.0,B-F,Reversed
2,3,1.0,1.0,F-F,Identical
3,4,2.0,1.0,B-F,Reversed
4,5,1.0,2.0,F-B,Reversed
...,...,...,...,...,...
7195,7196,2.0,1.0,B-F,Reversed
7196,7197,1.0,1.0,F-F,Identical
7197,7198,2.0,1.0,B-F,Reversed
7198,7199,1.0,2.0,F-B,Reversed


In [218]:
# merge condition and congruence
pairidx2cond = df_cond.loc[:, ["pair_idx", "cond"]].set_index("pair_idx").to_dict()["cond"]
pairidx2cong = df_cond.loc[:, ["pair_idx", "cong"]].set_index("pair_idx").to_dict()["cong"]
df_simu["cond"] = df_simu.apply(lambda x: pairidx2cond[x["pair_idx"]], axis=1)
df_simu["cong"] = df_simu.apply(lambda x: pairidx2cong[x["pair_idx"]], axis=1)
df_simu.head(24)

,session,list,test_itemno1,test_itemno2,s_resp,s_rt,csim,test_pos,test_item,correct_ans,order,rep,test,pair_idx,correct,cond,cong
0,0,0,51,-1,-1.0,-1.0,-1.000000,1,ASTRONAUT,1083,2,1,1,8,False,B-B,Identical
1,0,0,1202,-1,1551.0,3030.0,0.522379,2,ROCKET,1551,2,1,1,4,True,B-F,Reversed
2,0,0,979,-1,-1.0,-1.0,-1.000000,3,OPERATOR,142,1,1,1,11,False,F-F,Identical
3,0,0,134,-1,-1.0,-1.0,-1.000000,4,BLADE,105,1,1,1,9,False,F-B,Reversed
4,0,0,1081,-1,12.0,3870.0,0.535872,5,PLANE,1066,1,1,1,5,False,F-B,Reversed
5,0,0,357,-1,723.0,1660.0,0.587411,6,COMPANION,723,1,1,1,3,True,F-F,Identical
6,0,0,831,-1,-1.0,-1.0,-1.000000,7,LITERATURE,1435,2,1,1,7,False,B-B,Identical
7,0,0,1188,-1,-1.0,-1.0,-1.000000,8,RIB,641,2,1,1,12,False,B-F,Reversed
8,0,0,1260,-1,1315.0,2440.0,0.495662,9,SEAFOOD,1315,2,1,1,2,True,B-F,Reversed
9,0,0,12,-1,-1.0,-1.0,-1.000000,10,AIRPLANE,226,1,1,1,10,False,F-B,Reversed


In [219]:
# get f_in
sessions = np.unique(df_simu.session.to_numpy())
tmp_corr_fin = []
tmp_omean_fin = []
tmp_omax_fin = []

for sess in sessions:
    df_tmp = df_study.loc[df_study.session == sess]
    tmp1 = df_tmp.study_itemno1.to_numpy()
    tmp2 = df_tmp.study_itemno2.to_numpy()
    tmp = np.concatenate((tmp1, tmp2))
    tmp = np.sort(tmp)

    df_tmp1 = df_simu.loc[df_simu.session == sess]
    tmp_test = df_tmp1.test_itemno1
    tmp_corr = df_tmp1.correct_ans
    # tmp_test = df_simu.loc[df_simu.session == sess, 'test_itemno']
    # tmp_corr = df_simu.loc[df_simu.session == sess, 'correct_ans']
    testid = np.searchsorted(tmp, tmp_test)
    corrid = np.searchsorted(tmp, tmp_corr)

    fin_sess = f_dif[sess]
    # tmp_corr_fin = []
    # tmp_omean_fin = []
    # tmp_omax_fin = []
    for i in range(len(testid)):
        tmp_corr_fin.append(fin_sess[i][corrid[i]])
        tmp_omean_fin.append(np.mean(np.delete(fin_sess[i], corrid[i])))
        tmp_omax_fin.append(np.delete(fin_sess[i], corrid[i]).max())
    # df_simu.loc[df_simu.session == sess, 'corr_fin']= tmp_corr_fin
    # df_simu.loc[df_simu.session == sess, 'omean_fin'] = tmp_omean_fin
    # df_simu.loc[df_simu.session == sess, 'omax_fin'] = tmp_omax_fin

df_simu["corr_fin"] = tmp_corr_fin
df_simu["omean_fin"] = tmp_omean_fin
df_simu["omax_fin"] = tmp_omax_fin
df_simu

,session,list,test_itemno1,test_itemno2,s_resp,s_rt,csim,test_pos,test_item,correct_ans,order,rep,test,pair_idx,correct,cond,cong,corr_fin,omean_fin,omax_fin
0,0,0,51,-1,-1.0,-1.0,-1.000000,1,ASTRONAUT,1083,2,1,1,8,False,B-B,Identical,-0.405694,-0.833482,-0.546860
1,0,0,1202,-1,1551.0,3030.0,0.522379,2,ROCKET,1551,2,1,1,4,True,B-F,Reversed,-0.249198,-0.875270,-0.474359
2,0,0,979,-1,-1.0,-1.0,-1.000000,3,OPERATOR,142,1,1,1,11,False,F-F,Identical,-0.616804,-1.031146,-0.655247
3,0,0,134,-1,-1.0,-1.0,-1.000000,4,BLADE,105,1,1,1,9,False,F-B,Reversed,-0.390922,-0.986374,-0.487936
4,0,0,1081,-1,12.0,3870.0,0.535872,5,PLANE,1066,1,1,1,5,False,F-B,Reversed,-0.384794,-1.047561,-0.308906
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14395,99,5,1019,-1,-1.0,-1.0,-1.000000,20,PASSAGE,1143,1,1,2,7196,False,B-F,Reversed,-0.553291,-1.114922,-0.583641
14396,99,5,487,-1,788.0,1600.0,0.520041,21,DOORBELL,788,2,1,2,7189,True,B-B,Identical,0.214443,-0.964121,-0.206100
14397,99,5,723,-1,-1.0,-1.0,-1.000000,22,HOSTESS,1378,2,1,2,7192,False,F-B,Reversed,-0.278042,-1.038586,-0.302123
14398,99,5,196,-1,786.0,1380.0,0.583908,23,BULLY,786,1,1,2,7190,True,F-F,Identical,0.249928,-1.102903,-0.401473


In [220]:
df_fin = df_simu.groupby(["cong", "test"])[["corr_fin", "omean_fin", "omax_fin"]].mean().reset_index()
df_fin["dif"] = df_fin["corr_fin"] - df_fin["omax_fin"]
df_fin

,cong,test,corr_fin,omean_fin,omax_fin,dif
0,Identical,1,-0.264359,-0.996366,-0.322048,0.057688
1,Identical,2,-0.263912,-0.995125,-0.319682,0.055770
2,Reversed,1,-0.270103,-0.996100,-0.321826,0.051723
3,Reversed,2,-0.267878,-0.995890,-0.321313,0.053435


In [221]:
if SAVERES:
    df_simu.to_pickle("simu6b_data/simu6b_result.pkl")

## Analysis

In [222]:
# with open("simu6b_data/simu6b_result.pkl", "rb") as inp:
#     df_simu = pickle.load(inp)

In [223]:
# anal_perform used by pso
subjects = np.unique(df_simu.session)
inde_stats = []
reve_stats = []
for subj in subjects:
    df_subj_inde = df_simu.query(f"session == {subj} and cong == 'Identical'").copy()
    inde_stats.append(list(anal_perform(df_subj_inde)))

    df_subj_reve = df_simu.query(f"session == {subj} and cong == 'Reversed'").copy()
    reve_stats.append(list(anal_perform(df_subj_reve)))

In [224]:
np.array(inde_stats)

array([[0.33333333, 0.        , 0.05555556, 0.61111111, 0.99115044],
       [0.25      , 0.02777778, 0.02777778, 0.69444444, 0.98159509],
       [0.27777778, 0.        , 0.        , 0.72222222, 0.99820467],
       [0.27777778, 0.02777778, 0.        , 0.69444444, 0.99441341],
       [0.36111111, 0.02777778, 0.05555556, 0.55555556, 0.97326203],
       [0.30555556, 0.        , 0.        , 0.69444444, 0.99829642],
       [0.25      , 0.        , 0.        , 0.75      , 0.99808795],
       [0.19444444, 0.        , 0.02777778, 0.77777778, 0.99300699],
       [0.22222222, 0.02777778, 0.02777778, 0.72222222, 0.98021978],
       [0.30555556, 0.02777778, 0.        , 0.66666667, 0.99469027],
       [0.30555556, 0.        , 0.08333333, 0.61111111, 0.9865643 ],
       [0.25      , 0.        , 0.05555556, 0.69444444, 0.98973306],
       [0.19444444, 0.05555556, 0.02777778, 0.72222222, 0.96296296],
       [0.25      , 0.        , 0.05555556, 0.69444444, 0.98973306],
       [0.36111111, 0.        , 0.

In [225]:
np.array(reve_stats)

array([[0.25      , 0.05555556, 0.05555556, 0.63888889, 0.94553377],
       [0.33333333, 0.05555556, 0.02777778, 0.58333333, 0.97247706],
       [0.16666667, 0.13888889, 0.11111111, 0.58333333, 0.69908815],
       [0.22222222, 0.08333333, 0.11111111, 0.58333333, 0.84130982],
       [0.19444444, 0.08333333, 0.05555556, 0.66666667, 0.90909091],
       [0.22222222, 0.08333333, 0.11111111, 0.58333333, 0.84130982],
       [0.33333333, 0.05555556, 0.02777778, 0.58333333, 0.97247706],
       [0.27777778, 0.08333333, 0.11111111, 0.52777778, 0.85714286],
       [0.22222222, 0.08333333, 0.05555556, 0.63888889, 0.91606715],
       [0.19444444, 0.        , 0.05555556, 0.75      , 0.98795181],
       [0.16666667, 0.13888889, 0.05555556, 0.63888889, 0.83483483],
       [0.27777778, 0.08333333, 0.        , 0.63888889, 0.98591549],
       [0.27777778, 0.16666667, 0.11111111, 0.44444444, 0.71111111],
       [0.08333333, 0.13888889, 0.11111111, 0.66666667, 0.5520362 ],
       [0.16666667, 0.08333333, 0.

In [226]:
np.mean(inde_stats, axis=0)

array([0.27861111, 0.0175    , 0.02388889, 0.68      , 0.98741267])

In [227]:
np.mean(reve_stats, axis=0)

array([0.23583333, 0.06888889, 0.07833333, 0.61694444, 0.89513115])

In [228]:
inde_stats_mean = np.mean(inde_stats, axis=0)
reve_stats_mean = np.mean(reve_stats, axis=0)
inde_ground_truth = np.array([0.319, 0.006, 0.012, 0.663, 0.94])
reve_ground_truth = np.array([0.293, 0.049, 0.122, 0.537, 0.96])
err = (np.mean(np.power(inde_stats_mean - inde_ground_truth, 2)) + np.mean(np.power(reve_stats_mean - reve_ground_truth, 2))) / 2
err

0.002061127502649901