In [1]:
import numpy as np
import pickle
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import CMR_IA as cmr
import sys

sys.path.append("../../Modeling/fitting")
from optimization_utils import make_boundary
from object_funcs import anal_perform_6b as anal_perform

In [2]:
SAVERES = False

## Load Stimuli and Semantic Matrix

In [3]:
with open("simu6b_data/simu6b_design.pkl", "rb") as inp:
    df_study = pickle.load(inp)
    df_test = pickle.load(inp)
df_study = df_study.loc[df_study.session < 100]  # for testing
df_test = df_test.loc[df_test.session < 100]

In [4]:
df_study

,study_itemno1,study_itemno2,study_item1,study_item2,list,session
0,120,459,BELT,DIAPER,0,0
1,1315,1260,SKETCH,SEAFOOD,0,0
2,357,723,COMPANION,HOSTESS,0,0
3,1551,1202,VEAL,ROCKET,0,0
4,1081,1066,PLANE,PIGMENT,0,0
...,...,...,...,...,...,...
7195,1019,1143,PASSAGE,PUPIL,5,99
7196,293,1375,CHERRY,STEAM,5,99
7197,871,927,MARKET,MOVIE,5,99
7198,1392,1486,STREAM,TORTOISE,5,99


In [5]:
df_test

,test_itemno1,test_itemno2,test_item,correct_ans,order,rep,test,list,session,test_pos,pair_idx
0,51,-1,ASTRONAUT,1083,2,1,1,0,0,1,8
1,1202,-1,ROCKET,1551,2,1,1,0,0,2,4
2,979,-1,OPERATOR,142,1,1,1,0,0,3,11
3,134,-1,BLADE,105,1,1,1,0,0,4,9
4,1081,-1,PLANE,1066,1,1,1,0,0,5,5
...,...,...,...,...,...,...,...,...,...,...,...
14395,1019,-1,PASSAGE,1143,1,1,2,5,99,20,7196
14396,487,-1,DOORBELL,788,2,1,2,5,99,21,7189
14397,723,-1,HOSTESS,1378,2,1,2,5,99,22,7192
14398,196,-1,BULLY,786,1,1,2,5,99,23,7190


In [6]:
sem_mat = np.load("../wordpools/ltp_FR_similarity_matrix.npy")

## Run CMR-IA

In [7]:
# define parameters
params = cmr.make_default_params()
params.update(learn_while_retrieving=False, nitems_in_accumulator=96, use_new_context=True)  #! and 500?

# load pso results
_, _, what_to_fit = make_boundary(sim_name="6b")
optim_params = np.loadtxt("simu6b_data/6b_250408_200-200.txt")
for pname, pvalue in zip(what_to_fit, optim_params):
    params[pname] = pvalue
# params.update(beta_enc_inpair=0.05)  # for test, learn_while_retrieving=False
params

{'beta_enc': 0.866662,
 'beta_rec': 0.550292,
 'beta_cue': 0.971412,
 'beta_rec_post': 0.082552,
 'beta_distract': 0.480264,
 'beta_enc_inpair': -1,
 'phi_s': 3.254107,
 'phi_d': 0.477546,
 's_cf': 0.367439,
 's_fc': 0.255119,
 'kappa': 0.188473,
 'eta': 0.001319,
 'omega': 6.681985,
 'alpha': 0.790381,
 'lamb': 0.103443,
 'c_thresh': 0.451522,
 'c_thresh_itm': 0.5,
 'c_thresh_assoc': 0.5,
 'd_assoc': 0,
 'rec_time_limit': 60000.0,
 'dt': 10,
 'nitems_in_accumulator': 96,
 'max_recalls': 50,
 'learn_while_retrieving': False,
 'use_new_context': True,
 'psi_s': 0,
 'psi_c': 1,
 'c_s': 0,
 'thresh_sigma': 0,
 'ban_recall': None,
 'use_var_enc': False,
 'var_enc_p': None,
 'bad_enc_ratio': None,
 'recog_slope': 1,
 'use_flexible_thresh': False,
 'thresh_rate': 0,
 'thresh_kernel_len': 10,
 'gamma_fc': 0.360799,
 'gamma_cf': 0.345657}

In [8]:
for key in what_to_fit:
    print(f"{key}: {params[key]:.3f}")

beta_enc: 0.867
beta_rec: 0.550
beta_cue: 0.971
beta_rec_post: 0.083
beta_distract: 0.480
gamma_fc: 0.361
gamma_cf: 0.346
s_fc: 0.255
s_cf: 0.367
phi_s: 3.254
phi_d: 0.478
kappa: 0.188
lamb: 0.103
eta: 0.001
omega: 6.682
alpha: 0.790
c_thresh: 0.452


In [9]:
if SAVERES:
    # run the model
    df_simu, f_in, f_dif = cmr.run_success_multi_sess(params, df_study, df_test, sem_mat, mode="CR-CR")
    df_simu["test_pos"] = np.tile(np.arange(1, 25), 600)  # 6000
    # merge to get more info
    df_simu = df_simu.merge(df_test, on=["session", "list", "test_itemno1", "test_itemno2", "test_pos"])
    df_simu["correct"] = df_simu.s_resp == df_simu.correct_ans
    # save
    df_simu.to_pickle("simu6b_data/simu6b_result.pkl")
else:
    # load results
    with open("simu6b_data/simu6b_result.pkl", "rb") as inp:
        df_simu = pickle.load(inp)
df_simu

  1%|          | 1/100 [00:00<01:02,  1.59it/s]

100%|██████████| 100/100 [00:47<00:00,  2.09it/s]

CMR Time: 47.87981128692627


,session,list,test_itemno1,test_itemno2,s_resp,s_rt,csim,thresh,test_pos,test_item,correct_ans,order,rep,test,pair_idx,correct
0,0,0,51,-1,-1,-1,-1.000000,-1.000000,1,ASTRONAUT,1083,2,1,1,8,False
1,0,0,1202,-1,1551,2780,0.559819,0.451522,2,ROCKET,1551,2,1,1,4,True
2,0,0,979,-1,-1,-1,-1.000000,-1.000000,3,OPERATOR,142,1,1,1,11,False
3,0,0,134,-1,105,3700,0.613913,0.451522,4,BLADE,105,1,1,1,9,True
4,0,0,1081,-1,-1,-1,-1.000000,-1.000000,5,PLANE,1066,1,1,1,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14395,99,5,1019,-1,-1,-1,-1.000000,-1.000000,20,PASSAGE,1143,1,1,2,7196,False
14396,99,5,487,-1,788,980,0.567778,0.451522,21,DOORBELL,788,2,1,2,7189,True
14397,99,5,723,-1,-1,-1,-1.000000,-1.000000,22,HOSTESS,1378,2,1,2,7192,False
14398,99,5,196,-1,786,1300,0.617076,0.451522,23,BULLY,786,1,1,2,7190,True


## Analysis

In [10]:
# get condition and congruence
df_cond = df_simu.groupby(["pair_idx", "test"])["order"].mean().to_frame(name="corr_rate").reset_index()
df_cond = df_cond.pivot_table(index="pair_idx", columns="test", values="corr_rate").reset_index()
df_cond.columns = ["pair_idx", "test1", "test2"]


def cond(x):
    test1 = x["test1"]
    test2 = x["test2"]
    if test1 == 1 and test2 == 1:
        return "F-F"
    elif test1 == 1 and test2 == 2:
        return "F-B"
    elif test1 == 2 and test2 == 1:
        return "B-F"
    elif test1 == 2 and test2 == 2:
        return "B-B"


df_cond["cond"] = df_cond.apply(lambda x: cond(x), axis=1)
df_cond["cong"] = df_cond.apply(lambda x: "Identical" if x["cond"] == "F-F" or x["cond"] == "B-B" else "Reversed", axis=1)
df_cond

,pair_idx,test1,test2,cond,cong
0,1,1.0,1.0,F-F,Identical
1,2,2.0,1.0,B-F,Reversed
2,3,1.0,1.0,F-F,Identical
3,4,2.0,1.0,B-F,Reversed
4,5,1.0,2.0,F-B,Reversed
...,...,...,...,...,...
7195,7196,2.0,1.0,B-F,Reversed
7196,7197,1.0,1.0,F-F,Identical
7197,7198,2.0,1.0,B-F,Reversed
7198,7199,1.0,2.0,F-B,Reversed


In [11]:
# merge condition and congruence
pairidx2cond = df_cond.loc[:, ["pair_idx", "cond"]].set_index("pair_idx").to_dict()["cond"]
pairidx2cong = df_cond.loc[:, ["pair_idx", "cong"]].set_index("pair_idx").to_dict()["cong"]
df_simu["cond"] = df_simu.apply(lambda x: pairidx2cond[x["pair_idx"]], axis=1)
df_simu["cong"] = df_simu.apply(lambda x: pairidx2cong[x["pair_idx"]], axis=1)
df_simu.head(24)

,session,list,test_itemno1,test_itemno2,s_resp,s_rt,csim,thresh,test_pos,test_item,correct_ans,order,rep,test,pair_idx,correct,cond,cong
0,0,0,51,-1,-1,-1,-1.000000,-1.000000,1,ASTRONAUT,1083,2,1,1,8,False,B-B,Identical
1,0,0,1202,-1,1551,2780,0.559819,0.451522,2,ROCKET,1551,2,1,1,4,True,B-F,Reversed
2,0,0,979,-1,-1,-1,-1.000000,-1.000000,3,OPERATOR,142,1,1,1,11,False,F-F,Identical
3,0,0,134,-1,105,3700,0.613913,0.451522,4,BLADE,105,1,1,1,9,True,F-B,Reversed
4,0,0,1081,-1,-1,-1,-1.000000,-1.000000,5,PLANE,1066,1,1,1,5,False,F-B,Reversed
5,0,0,357,-1,723,1680,0.616534,0.451522,6,COMPANION,723,1,1,1,3,True,F-F,Identical
6,0,0,831,-1,-1,-1,-1.000000,-1.000000,7,LITERATURE,1435,2,1,1,7,False,B-B,Identical
7,0,0,1188,-1,-1,-1,-1.000000,-1.000000,8,RIB,641,2,1,1,12,False,B-F,Reversed
8,0,0,1260,-1,1315,1300,0.551023,0.451522,9,SEAFOOD,1315,2,1,1,2,True,B-F,Reversed
9,0,0,12,-1,-1,-1,-1.000000,-1.000000,10,AIRPLANE,226,1,1,1,10,False,F-B,Reversed


In [2]:
# # get f_in
# sessions = np.unique(df_simu.session.to_numpy())
# tmp_corr_fin = []
# tmp_omean_fin = []
# tmp_omax_fin = []

# for sess in sessions:
#     df_tmp = df_study.loc[df_study.session == sess]
#     tmp1 = df_tmp.study_itemno1.to_numpy()
#     tmp2 = df_tmp.study_itemno2.to_numpy()
#     tmp = np.concatenate((tmp1, tmp2))
#     tmp = np.sort(tmp)

#     df_tmp1 = df_simu.loc[df_simu.session == sess]
#     tmp_test = df_tmp1.test_itemno1
#     tmp_corr = df_tmp1.correct_ans
#     # tmp_test = df_simu.loc[df_simu.session == sess, 'test_itemno']
#     # tmp_corr = df_simu.loc[df_simu.session == sess, 'correct_ans']
#     testid = np.searchsorted(tmp, tmp_test)
#     corrid = np.searchsorted(tmp, tmp_corr)

#     fin_sess = f_dif[sess]
#     # tmp_corr_fin = []
#     # tmp_omean_fin = []
#     # tmp_omax_fin = []
#     for i in range(len(testid)):
#         tmp_corr_fin.append(fin_sess[i][corrid[i]])
#         tmp_omean_fin.append(np.mean(np.delete(fin_sess[i], corrid[i])))
#         tmp_omax_fin.append(np.delete(fin_sess[i], corrid[i]).max())
#     # df_simu.loc[df_simu.session == sess, 'corr_fin']= tmp_corr_fin
#     # df_simu.loc[df_simu.session == sess, 'omean_fin'] = tmp_omean_fin
#     # df_simu.loc[df_simu.session == sess, 'omax_fin'] = tmp_omax_fin

# df_simu["corr_fin"] = tmp_corr_fin
# df_simu["omean_fin"] = tmp_omean_fin
# df_simu["omax_fin"] = tmp_omax_fin
# df_simu

In [1]:
# df_fin = df_simu.groupby(["cong", "test"])[["corr_fin", "omean_fin", "omax_fin"]].mean().reset_index()
# df_fin["dif"] = df_fin["corr_fin"] - df_fin["omax_fin"]
# df_fin

In [16]:
# anal_perform used by pso
subjects = np.unique(df_simu.session)
inde_stats = []
reve_stats = []
for subj in subjects:
    df_subj_inde = df_simu.query(f"session == {subj} and cong == 'Identical'").copy()
    inde_stats.append(list(anal_perform(df_subj_inde)))
    df_subj_reve = df_simu.query(f"session == {subj} and cong == 'Reversed'").copy()
    reve_stats.append(list(anal_perform(df_subj_reve)))

In [17]:
np.array(inde_stats)

array([[0.36111111, 0.02777778, 0.05555556, 0.55555556, 0.97326203],
       [0.27777778, 0.        , 0.05555556, 0.66666667, 0.99032882],
       [0.33333333, 0.02777778, 0.02777778, 0.61111111, 0.98412698],
       [0.38888889, 0.02777778, 0.02777778, 0.55555556, 0.98497496],
       [0.36111111, 0.02777778, 0.02777778, 0.58333333, 0.98461538],
       [0.30555556, 0.02777778, 0.        , 0.66666667, 0.99469027],
       [0.36111111, 0.02777778, 0.        , 0.61111111, 0.99507389],
       [0.19444444, 0.02777778, 0.02777778, 0.75      , 0.97841727],
       [0.33333333, 0.        , 0.05555556, 0.61111111, 0.99115044],
       [0.36111111, 0.        , 0.        , 0.63888889, 0.9984252 ],
       [0.38888889, 0.        , 0.02777778, 0.58333333, 0.9952    ],
       [0.30555556, 0.02777778, 0.        , 0.66666667, 0.99469027],
       [0.27777778, 0.05555556, 0.02777778, 0.63888889, 0.97005988],
       [0.30555556, 0.        , 0.05555556, 0.63888889, 0.9907919 ],
       [0.36111111, 0.        , 0.

In [18]:
np.array(reve_stats)

array([[0.27777778, 0.05555556, 0.11111111, 0.55555556, 0.90066225],
       [0.41666667, 0.02777778, 0.02777778, 0.52777778, 0.98522167],
       [0.25      , 0.08333333, 0.11111111, 0.55555556, 0.85035629],
       [0.30555556, 0.08333333, 0.        , 0.61111111, 0.9865643 ],
       [0.16666667, 0.11111111, 0.08333333, 0.63888889, 0.81305638],
       [0.27777778, 0.08333333, 0.05555556, 0.58333333, 0.92537313],
       [0.36111111, 0.05555556, 0.08333333, 0.5       , 0.93230174],
       [0.38888889, 0.05555556, 0.08333333, 0.47222222, 0.93333333],
       [0.25      , 0.11111111, 0.        , 0.63888889, 0.98004435],
       [0.19444444, 0.        , 0.16666667, 0.63888889, 0.9637883 ],
       [0.19444444, 0.08333333, 0.08333333, 0.63888889, 0.87002653],
       [0.30555556, 0.08333333, 0.08333333, 0.52777778, 0.89640592],
       [0.5       , 0.08333333, 0.        , 0.41666667, 0.98786828],
       [0.22222222, 0.08333333, 0.11111111, 0.58333333, 0.84130982],
       [0.19444444, 0.08333333, 0.

In [19]:
np.mean(inde_stats, axis=0)

array([0.32777778, 0.01972222, 0.02388889, 0.62861111, 0.98721735])

In [20]:
np.mean(reve_stats, axis=0)

array([0.29      , 0.06333333, 0.07027778, 0.57638889, 0.92428728])

### Err Check

In [21]:
inde_stats_mean = np.mean(inde_stats, axis=0)
reve_stats_mean = np.mean(reve_stats, axis=0)
inde_ground_truth = np.array([0.319, 0.006, 0.012, 0.663, 0.94])
reve_ground_truth = np.array([0.293, 0.049, 0.122, 0.537, 0.96])
err = (np.mean(np.power(inde_stats_mean - inde_ground_truth, 2)) + np.mean(np.power(reve_stats_mean - reve_ground_truth, 2))) / 2
err

0.0009535283704792204