In [1]:
import pandas as pd
import numpy as np
import pickle
from scipy.io import loadmat
from numpy.linalg import norm

In [2]:
# 16-faces to produce similarity matrix
mat = loadmat('simu8_data/simu8_Experiment1.mat')
mdata = mat['events']
face_corrd = mdata['facecoordinates']
face_corrd_list = []
for x in face_corrd:
    if len(x[0].tolist()) != 0:
        face_corrd_list.append(x[0].tolist()[0])
face_corrd_16 = np.unique(face_corrd_list,axis=0)
face_corrd_16 = [np.array(x) for x in face_corrd_16]
face_corrd_16

[array([-1.725,  0.84 ,  0.301, -0.444]),
 array([-1.298,  1.292,  0.925,  0.165]),
 array([-1.249, -0.599, -1.242, -0.532]),
 array([-1.079, -0.828, -1.271,  0.682]),
 array([-0.723,  0.215,  1.953,  0.039]),
 array([-0.342,  0.087,  1.801, -0.789]),
 array([-0.248, -1.602,  0.534, -0.86 ]),
 array([-0.075,  1.511, -1.029, -0.483]),
 array([ 0.268, -0.468, -0.106,  2.199]),
 array([ 0.384,  1.504, -0.951,  0.552]),
 array([ 0.402, -1.269, -0.481, -1.391]),
 array([ 0.484, -0.39 , -1.059,  1.69 ]),
 array([ 0.901,  0.706,  1.06 , -1.079]),
 array([ 1.128,  0.942,  0.022, -1.137]),
 array([ 1.284, -1.257, -0.231,  0.891]),
 array([ 1.886, -0.683, -0.227,  0.498])]

In [3]:
face_sim = np.zeros((16,16))
for i in range(16):
    for j in range(16):
        A = face_corrd_16[i]
        B = face_corrd_16[j]
        cosine = np.dot(A,B)/(norm(A)*norm(B))
        face_sim[i,j] = (cosine + 1) / 2
face_sim

array([[1.        , 0.93034729, 0.69633137, 0.5608128 , 0.73951112,
        0.69541804, 0.45071529, 0.67285978, 0.29364281, 0.5091855 ,
        0.33728731, 0.23189041, 0.47842681, 0.41314568, 0.03557643,
        0.00310219],
       [0.93034729, 1.        , 0.45112587, 0.41026476, 0.85140094,
        0.75438823, 0.32259223, 0.63068208, 0.42629748, 0.58378634,
        0.15288862, 0.28687736, 0.56980733, 0.44583756, 0.09605195,
        0.09597315],
       [0.69633137, 0.45112587, 1.        , 0.89874757, 0.29366121,
        0.31347485, 0.64380371, 0.59880055, 0.37544439, 0.4330289 ,
        0.70773639, 0.50560224, 0.1879537 , 0.30594147, 0.36716467,
        0.26021031],
       [0.5608128 , 0.41026476, 0.89874757, 1.        , 0.27674996,
        0.18056485, 0.5433908 , 0.47444666, 0.6928017 , 0.49012758,
        0.53554168, 0.77758737, 0.01604547, 0.11990958, 0.5695343 ,
        0.39794875],
       [0.73951112, 0.85140094, 0.29366121, 0.27674996, 1.        ,
        0.94854456, 0.60547751, 

In [4]:
s_mat = np.zeros((32,32))
np.fill_diagonal(s_mat,1)
s_mat[0:16,0:16] = face_sim
s_mat

array([[1.        , 0.93034729, 0.69633137, ..., 0.        , 0.        ,
        0.        ],
       [0.93034729, 1.        , 0.45112587, ..., 0.        , 0.        ,
        0.        ],
       [0.69633137, 0.45112587, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [5]:
np.save("simu8_data/simu8_smat.npy",s_mat)

### Distance

In [6]:
face_distance = np.zeros((16,16))
for i in range(16):
    for j in range(16):
        A = face_corrd_16[i]
        B = face_corrd_16[j]
        distance = norm(A-B)
        face_distance[i,j] = distance.round(4)
face_distance

array([[0.    , 1.0709, 2.1647, 2.6341, 2.0873, 2.202 , 2.8935, 2.2233,
        3.5825, 2.7292, 3.2373, 3.5772, 2.8095, 2.9509, 3.9391, 4.0651],
       [1.0709, 0.    , 2.9597, 3.1036, 1.601 , 2.0108, 3.2682, 2.4045,
        3.2787, 2.558 , 3.7211, 3.5024, 2.5971, 2.9187, 3.8765, 3.934 ],
       [2.1647, 2.9597, 0.    , 1.2474, 3.3872, 3.2587, 2.2956, 2.4245,
        3.3268, 2.8895, 2.1194, 2.8316, 3.4531, 3.1605, 3.1458, 3.4535],
       [2.6341, 3.1036, 1.2474, 0.    , 3.4673, 3.603 , 2.6316, 2.8098,
        2.367 , 2.7745, 2.7036, 1.9225, 3.8481, 3.6034, 2.6255, 3.1521],
       [2.0873, 1.601 , 3.3872, 3.4673, 0.    , 0.9329, 2.5197, 3.3562,
        3.2177, 3.4034, 3.3819, 3.6906, 2.2194, 3.0111, 3.4192, 3.5463],
       [2.202 , 2.0108, 3.2587, 3.603 , 0.9329, 0.    , 2.1147, 3.194 ,
        3.6394, 3.4506, 2.8217, 3.9032, 1.6004, 2.4855, 3.3766, 3.3654],
       [2.8935, 3.2682, 2.2956, 2.6316, 2.5197, 2.1147, 0.    , 3.508 ,
        3.3644, 3.7743, 1.3585, 3.3234, 2.6404, 2.9503, 2.

In [7]:
np.save("siu8_data/simu8_distance.npy",face_distance)